### ISSUE TITLE
Getting save errors with various class construtions

### ISSUE THREAD

**Issue by dgonzo** [johnbywater/eventsourcing#106]
I'm still trying to tackle an example app and making progress in some directions but still failing to understand the fundamentals in this library so please know that I'm super appreciative of your patience. Once I figure this out I hope to make the example library very clear and runnable.

I'm trying to understand how best to construct classes using either the `WithReflexiveMutator` or `TimestampedVersionedEntity`. I've created the same basic class `user` with the two modalities and getting different errors.

I'd love to understand the errors, yes. But I'd also like to get a decent representation of both so I'm 100% open to feedback, critique, even eye-rolling and muttered swears. 

Here's what I have so far: https://github.com/dgonzo/eventsourcing-kanban. See the README for the errors I'm seeing and the links to the relevant files.

**Comment by johnbywater** [comment]
I'll take a look ;-)

**Comment by johnbywater** [comment]
The first error follows from attempting to snapshot a `Collection`, which has a `set`, so can't be serialised with the default JSON encoder. So you can either extend the JSON encoder and decoder to support the type `set`. Or you can change the Collection to use a `list`, which is supported. Let's do the former, and then we can fix the default JSON encoder in the next version of the library to support sets.

**Comment by johnbywater** [comment]
The second error is a Python `NameError`, which follows from the exception class not being imported.

**Comment by johnbywater** [comment]
What's this?

```
hypothesis.errors.FailedHealthCheck: Data generation is extremely slow: Only produced 9 valid examples in 1.09 seconds (0 invalid ones and 0 exceeded maximum size). Try decreasing size of the data you're generating (with e.g.average_size or max_leaves parameters).
E                        See https://hypothesis.readthedocs.io/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.too_slow to the suppress_health_check settings for this test.
```

**Comment by johnbywater** [comment]
I just pushed some changes in PR to your repo.
https://github.com/dgonzo/eventsourcing-kanban/pull/1

**Comment by johnbywater** [comment]
One thought: about the UnitOfWork, I think it's a nice way to go, to instantiate the application object for each request. But unfortunately at the moment, if there are many threads, and if each constructs its own application object, each application will receive all event from every application currently instantiated, because the pub-sub mechanism uses a module level dict, so they aren't separated.

That means, unless we fix up the pub-sub mechanism, you will want to have only one application object per process.

There might be a better way to do it, such as scoping the subscriptions and the publication of events to be scoped either to a thread or a request (like SQLAlchemy). But at the moment, it's perhaps best to just have one application object. So "unit of work" might not be the best name for the application.... I suggest keeping the "unit of work" but have it use an application object that is constructed once in the process, after it starts but before any requests are handled (to avoid race conditions in setting up the application object).

FWIW I tried to write about this in the documentation, here:
http://eventsourcing.readthedocs.io/en/v3.0.0/topics/user_guide/deployment.html#application-object

**Comment by johnbywater** [comment]
If it helps, you can think of the Application object as "configuration", it's really just picking options. It's not really so different from defining a namedtuple, it's Python code that can run once before your code "really" starts.

**Comment by dgonzo** [comment]
@johnbywater thank you.
