### ISSUE TITLE
Recommended way to store plain records

### ISSUE THREAD

**Issue by dgonzo** [johnbywater/eventsourcing#107]
I've been struggling with the simple use case of needing to store an email lookup alongside the event store.

Maybe I'm thinking of this wrong but in my mind, the simplest way to store an account email would be an "email" table that enforces uniqueness of the email. This would be a plain-jane table with an entity_id primary key and an email column.

However, I'm hitting an escalating complexity trying to either work with the eventsourcing global scoped session or trying to work around it with a separate session (e.g. records are colliding or I'm hitting a locked database.)

What is the recommended way to do something like an email store? The email is stored in the event_store as well but it's in TEXT blog and sorting through versions and then doing a full-text search seems like a huge over-invention when standard rdbms tables do this "for free".

**Comment by johnbywater** [comment]
If you want to resolve an email address to a user, then you can just define an EmailAddress entity, with attributes for the actual email address and the user ID. You can have a factory that uses a UUIDv5 to generate a UUID from an email address, and publishes an EmailAddress.Created event with those three things. You can have a repository that accepts an email as a key, because it extends __getitem__ by making the UUIDv5 from the email address and calling the super method with that ID. Then you can have a policy that registers email addresses whenever a user is created, or if the email address is updated.

**Comment by johnbywater** [comment]
If you want to do substring searches, then, of course, you can have a separate table with an index. An alternative is an event sourced suffix tree. There's some working code for an event sourced suffix tree index in an older version of the library, but I need to update it before reintroducing it in a future version.

**Comment by johnbywater** [comment]
To avoid account enumeration issues you can adjust the policy above to respond to "email verified" events, so that I can't discover that you have registered your email address by my attempting to register your email address. But then you will then need to support verifying email addresses.

**Comment by johnbywater** [comment]
Regarding the database sessions, if you are using a custom table to store things, then it essentially has nothing to do with the eventsourcing library, so you just need to think about which session you want to use for that. Perhaps if it's the same framework as we were discussing before, you can use the session arg of the request methods?

**Comment by dgonzo** [comment]
@johnbywater I think your first idea is pretty solid and I'll try that. A second database seems like a good option too and was what I was thinking initially but I'm not sure I want to juggle it if I don't have too. Thanks for the guidance.
