### ISSUE TITLE
Projections and domain code duplication

### ISSUE THREAD

**Issue by vladimirnani** [johnbywater/eventsourcing#139]
I update my domain model state in AggregateRoot by using mutators in events. So my state is consistent in the domain model.

I find quite often that the read model which i rebuild in projections is exactly same as state i have in domain model. But because I am subscribed to an event i have to do kinda the same logic of calculation and assignment of the state. 

Ideally my projection would just dump the domain model state into a read store (ES in my particular case) and deal with some versioning conflicts. 

Not sure how to structure it. 

```
# domain
class SomethingHappend(Event, AggregateRoot.Event):
    def mutate(self, state):
        state.calculated = self.data * 100
```

```
# projection
@subscribe_to(SomethingHappend)
def on_something(event):
    state = get_from_read_db(event.originator_id)
    state.calculated = self.data * 100
    save_to_read_db(state)
```

**Comment by johnbywater** [comment]
The rules of thumb I use for aggregates: 1. do computational work in the aggregate command methods; 2. trigger an event with the results of that work; 3. apply the results of the work to the aggregate state and publish the event.

After that, aggregates are already projections, so if your read model (non-aggregate projection) needs to use the current state of the aggregate, then surely you can just get the aggregate (from the repository) and use it to update ES. It you are concerned that other events may have happened in the aggregate since the event you are processing, you could get the aggregate at the version of the event.

I guess reading ES before updating is perhaps not such a great idea. It just seems like the flow is going in the wrong direction.

If you want to make it more complicated, you could project a sequence of commands that can be used to update ES, and then have something else work through the commands. You could then more easily rebuild ES by running the ES commands, which would avoid working through all the aggregates.

It looks like you are simply using events as they happen. If you were tracking notifications, something I didn't really implement yet in the library, the biggest trouble with writing into other systems reliably is writing into that system, atomically with the changes you make, the position in the sequence you are consuming. Without tha, there's always the risk that you can get out of sync.

**Comment by vladimirnani** [comment]
Thanks for the reply.

So i should can change my code to the following:

```
# domain
def do_somthing(self, data)
    calculated = data * 100
    self.__trigger_event__(SomethingHappend, calculated=calculated)

class SomethingHappend(Event, AggregateRoot.Event):
    def mutate(self, state):
        state.calculated = self.calculated
```
Make sense, so then the mutate in an event should remain thin.

I have tried to get an aggregate right from the repo but because we invoke handlers sequentially it will only be there after save. So i cannot find it in `@subscribe_to(Created)` for example.

Yes for now as a test i use the naive event subscription for updating read model. I would like to look into the notification log thing.

**Comment by johnbywater** [comment]
The subscriptions are called in the order they are registered, so I guess your handler is getting called before the persistence policy's handler? They should be called in the order they are subscribed, so I guess your decorated handler is being subscribed by the decorator before the persistency policy subscribes? You can easily see what the order is, e.g. in a debugger by setting breakpoints in the library's subscribe() function. Or by putting a breakpoint in your handler and one in the persistence policy's handler. Or both if you aren't sure the order of subscription is being respected when publishing events. If so, make sure you are constructing the persistence policy before the decorated handler is defined? Just guessing...

By the way, if you're doing this in tests, then remember if necessary, after using the decorator, you can return to having nothing subscribed by clearing the `_event_handlers` dict with its `clear()` method. I find it more convenient to call `subscribe` and `unsubscribe` in tests, but you can define a function in a test case that uses the decorator and then call `_event_handlers.clear()` afterwards to run a different test. That's what happens when [the documentation](http://eventsourcing.readthedocs.io/en/v5.1.0/topics/projections.html) gets tested anyway.

**Comment by johnbywater** [comment]
I'll try to crack on with the process code. I was trying to figure out how to scale throughput. The problem is that if all events are put in a single sequence, there's obviously a limit. But if events are put in different notification sequences, for example if the application aggregates were partitioned by user, and all events in that partition go in the same notification sequence, how do we "catch up" downstream without essentially serialising everything, maybe resorting to timestamps to sequence across the independent partitions. But then I realised that if notifications in a process are indexed by event, so you can find the notifications for the last events applied to the aggregates in the state when a process starts to use them (which is simple to do), then the pending events produced by running commands on aggregates can be written with notification records that refer to the notifications for those last events. If those notifications happen to be in the same partition, they can be dropped, otherwise the consumer of the notification will know to wait for progress in the other partition to reach a particular position, before it continues. That's not serialising everything, and I think it will maintain the causal relations between events without resorting to timestamps and merge sorting (which I nearly did).

The state wouldn't actually need to be partitioned by user, and aggregate events could be notified in any of the notification logs. There could be one thread (or operating system process) per notification log, and you could just increase or decrease the number of logs and processes, and hence scale throughput. I think it might just work...
