### ISSUE TITLE
Question: inject services into aggregates.

### ISSUE THREAD

**Issue by MidnightWonderer** [johnbywater/eventsourcing#163]
Hello  
I am new to your library.  
I want to create event sourced aggregate with service injected into the constructor of aggregates.  
  
Say I want to create an aggregate that handles a command that contains a password.  
I need to hash the password before constructing the event.  
  
Something like this:  
```python
class Registration(AggregateRoot):
    def __init__(self, *args, **kwargs):
        # injected
        self._id = kwargs.pop('id')
        self._hash_password = kwargs.pop('hash_password')
        super().__init__(*args, **kwargs)
        # aggregate state
        self._hashed_password = None

    def set_password(self, **kwargs):
        if self._hashed_password:
            raise InvalidOperation
        self.__trigger_event__(
            PasswordSet,
            **PasswordSet.validate({
                'id': self._id,
                'hashed_password': self._hash_password(kwargs.pop('password')),
            })
        )

    def on_event(self, event):
        if isinstance(event, PasswordSet):
            self._hashed_password = event.hashed_password
```
as you can see here I inject "hash_password" service which is actually a python method.  
However, when I try to construct the aggregate.  
```python
        test_registration_aggregate = Registration.__create__(
            id='abcd',
            hash_password=lambda x: x,
        )
```
I got the error
```
Traceback (most recent call last):
  File "/home/runner/app/user_registrations/tests/practice.py", line 20, in setUp
    hash_password=lambda: 'new_password',
  File "/home/runner/.local/share/virtualenvs/app-i5Lb5gVx/lib/python3.7/site-packages/eventsourcing/domain/model/entity.py", line 229, in __create__
    return super(EntityWithHashchain, cls).__create__(*args, **kwargs)
  File "/home/runner/.local/share/virtualenvs/app-i5Lb5gVx/lib/python3.7/site-packages/eventsourcing/domain/model/entity.py", line 63, in __create__
    **kwargs
  File "/home/runner/.local/share/virtualenvs/app-i5Lb5gVx/lib/python3.7/site-packages/eventsourcing/domain/model/events.py", line 167, in __init__
    self.__dict__['__event_hash__'] = self.__hash_object__(self.__dict__)
  File "/home/runner/.local/share/virtualenvs/app-i5Lb5gVx/lib/python3.7/site-packages/eventsourcing/domain/model/events.py", line 145, in __hash_object__
    return hash_object(cls.__json_encoder_class__, obj)
  File "/home/runner/.local/share/virtualenvs/app-i5Lb5gVx/lib/python3.7/site-packages/eventsourcing/utils/hashing.py", line 12, in hash_object
    cls=json_encoder_class,
  File "/home/runner/.local/share/virtualenvs/app-i5Lb5gVx/lib/python3.7/site-packages/eventsourcing/utils/transcoding.py", line 133, in json_dumps
    cls=cls,
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/runner/.local/share/virtualenvs/app-i5Lb5gVx/lib/python3.7/site-packages/eventsourcing/utils/transcoding.py", line 23, in iterencode
    return super(ObjectJSONEncoder, self).iterencode(o, _one_shot=_one_shot)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/runner/.local/share/virtualenvs/app-i5Lb5gVx/lib/python3.7/site-packages/eventsourcing/utils/transcoding.py", line 65, in default
    return JSONEncoder.default(self, obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type builtin_function_or_method is not JSON serializable
```
So I assumed that whatever passed into `__create__` should be serializable
but how else do I pass domain services into aggregates.

**Comment by MidnightWonderer** [comment]
Another question related to this one:  
  
Why do all parameters pass into the aggregate need to be serializable?  
In my understanding, we never serialize aggregates or anything related to them anywhere (unless we use snapshotting.)  
The only thing needs to be serializable are events. no?

**Comment by johnbywater** [comment]
The parameters need to be serializable because they are used firstly in a Created event: the Created event attributes is used as the AggregateRoot constructor args.

Functions aren't serializable, but if you pass in a normal Python object class instance, that has the function you want, that would that be serializable? Then you can call the method on the object.

**Comment by MidnightWonderer** [comment]
Hi, John thank you for the great library.  
I just misunderstood the `__create__` method  
I am new to both python and your library I thought it serves as a factory method (class construction).  
  
On this topic I want to share my experience with you:  
In my DDD experience, the Domain Event has been developed from business languages which hardly contains anything around "CRUD".  (Especially create, read and delete which I never once encountered)  
There might be more suitable words to describe the event (e.g. "UserRegistered" which is more accurate than "Created")  
  
However, in this library, `__create__` act like a constructor and also triggering an event which is quite a surprise for me.  
It seems I can work around that by simply using the constructor instead of `__create__` like:  
```python
class Registration(BaseAggregateRoot):
    def __init__(self, **kwargs):
        ...
        super().__init__(
            id=registration_id,
            __version__=0,
            **kwargs
        )
        ...
```
  
But I still have a lot of unknown I want to ask you about.  
May I hijack this issues and use it as a discussion thread?  
  
In the AggregateRoot class, there is `__save__` method.  
```python
    def __save__(self):
        batch_of_events = self.__batch_pending_events__()
        if batch_of_events:
            self.__publish_to_subscribers__(batch_of_events)
```
Which essentially just a proxy to `publish`.  
I see nothing related to event persistence before triggering event handlers.  
I wonder if this by design? How does the event store work with aggregate root? Should I handle event persistency somewhere outside aggregate?  
  
And since I am new to python to me it seems that `publish` and co. are all singleton.  
Does this mean we can only have exactly one event bus for the entire python process?

**Comment by johnbywater** [comment]
You can construct an entity directly. The `__create__()` factory method does that indirectly by firstly constructing an event and then using the entity class to construct an entity instance. That way you can persist the event, and replay it, to get the entity (which is the purpose of the repository).

The `DomainEntity` class just publishes events that are triggered. That way, each event is persisted in a separate transaction. So if a command results in more than one event, and the database goes away for a little bit just after transacting the first event, the others will be lost, and the command will result in an intermediate state being persisted. So the `AggregateRoot` class allows more than one event to be transacted into the database at the same time. That means all the events from a command will be persisted or none of them will, which means the command either completely works or it completely fails. The consequence is that the events aren't published when they are triggered, but held as "pending" the call to `__save__()`. When `__save__()` is called, the pending events are published as a list. The library's persistence infrastructure can handle both individual events, and lists of events, so when a list of events is published, it can be transacted into the database.

Yes, the pub-sub mechanism is essentially a singleton for the entire python process. The `persist_event_type` arg (e.g. on Application classes) can be used to distinguish which application persists which events.

Good point about CRUD. The names of events in the library e.g. "Created", "AttributeChanged", and "Discarded" are used to define an entity lifecycle that is recognisable as CRUD, with the strong expectation that users like you will want and need to define your own events. If you want to start with "Registered" instead of "Created", then perhaps the easiest thing is to define a `Registered` event that inherits from the library's `Created` event and define a factory method called `register()` that calls `__create__()`. That way, the functionality implemented by the library's `Created` event and `__create__()` methods can be invoked, whilst the names can be chosen to work within the project's ubiquitous language. The `__create__()` method has an arg called `event_class` which can be used to pass in your `Registered` event class, so it is used instead of the `Created` event. Of course, that functionality can be duplicated, or replaced with something better.

Of course you can make this issue into a discussion. Feel free to ask more questions! Thanks for your interest in this project! :-)
