### ISSUE TITLE
What to do when changing the code location of an entity class?

### ISSUE THREAD

**Issue by gregmuellegger** [johnbywater/eventsourcing#165]
Hi, thanks for this excellent library.

I was wondering what I would do if I wanted to restructure my codebase and move a domain entity class from one module to another. As far as I can tell, the `eventsourcing` library uses `get_topic` to determine the topic used in the DB to store the type of an event or entity.

Is there a way to swap the implementation of `get_topic` and `retrieve_topic` (maybe via dependency injection) in order to have a custom mapping in place that keeps backwards compatibility?

As an example, in original implementation the entity `World` lives in `myapp.domain.world.World` and therefore gets the topic `myapp.domain.world#World`. Now when relocating to `myapp2.world.World` the topic will be `myapp2.world#World` which is a mismatch.

**Comment by gregmuellegger** [comment]
> If you can use a subclass of `SequencedItemMapper` in your application, then you could extend the `SequencedItemMapper` method `get_class_and_state(topic, data)` to do what you need.

Ah, that sounds like the proper solution. Thanks for that idea.

Rewriting the events might also be ok, however wouldn't that interfere with the cryptographic hashing of the events?

**Comment by johnbywater** [comment]
Comments probably apply to the develop branch, but you can do something similar with the code on the master branch (released on PyPI).

If you rewrite the events and use the hash chain, then you will need to reproduce the hash chain, because the topic is included in the hash data to distinguish between events of different types that otherwise have the same attributes.
