### ISSUE TITLE
Hitting eventsourcing.exceptions.EventHashError

### ISSUE THREAD

**Issue by AlanFoster** [johnbywater/eventsourcing#170]
Hi there, I'm currently playing around with the library and I'm hitting the following run time error when running two commands in a row and then attempting to look up the aggregate root id within `app.repository`:

> python3.7/site-packages/eventsourcing/domain/model/events.py", line 139, in __check_hash__
>    raise EventHashError()
> eventsourcing.exceptions.EventHashError

The code is available here https://github.com/AlanFoster/eventsourcing and the error is reproducible with:

```
pipenv shell
pipenv install
pipenv run python main.py
```

From what I can tell this might be a bug within the library, but I'm not sure just yet! I'd be keen to know your thoughts :+1:

**Comment by johnbywater** [comment]
Thanks for raising the issue @AlanFoster Please could you provide a full traceback?

Looking at the code, it might be that dataclasses aren't supported. Does it work if you avoid them? If it's dataclasses that is causing the problem, perhaps we can figure out what is happening with the hashing? maybe they are being serialised in someway that messes things up? more than happy to make sure this is fixed, whatever it is 👍

**Comment by johnbywater** [comment]
@AlanFoster please note, if you don't need the event hashing, you can inherit from `BaseAggregateRoot`. But if there is a problem with the transcoding of data classes, it would be good to add support for that.

**Comment by AlanFoster** [comment]
@johnbywater Thanks for the fast response!

The full stack trace is:

```
$ pipenv run python main.py

Traceback (most recent call last):
  File "main.py", line 94, in <module>
    assert report.id in app.repository
  File "/Users/admin/.local/share/virtualenvs/eventsourcing-ADotesgZ/lib/python3.7/site-packages/eventsourcing/infrastructure/eventsourcedrepository.py", line 12, in __contains__
    return self.get_entity(entity_id) is not None
  File "/Users/admin/.local/share/virtualenvs/eventsourcing-ADotesgZ/lib/python3.7/site-packages/eventsourcing/infrastructure/eventsourcedrepository.py", line 58, in get_entity
    return self.get_and_project_events(entity_id, gt=gt, lte=at, initial_state=initial_state)
  File "/Users/admin/.local/share/virtualenvs/eventsourcing-ADotesgZ/lib/python3.7/site-packages/eventsourcing/infrastructure/eventsourcedrepository.py", line 97, in get_and_project_events
    return self.project_events(initial_state, domain_events)
  File "/Users/admin/.local/share/virtualenvs/eventsourcing-ADotesgZ/lib/python3.7/site-packages/eventsourcing/infrastructure/eventplayer.py", line 36, in project_events
    return reduce(self._mutator_func or self.mutate, domain_events, initial_state)
  File "/Users/admin/.local/share/virtualenvs/eventsourcing-ADotesgZ/lib/python3.7/site-packages/eventsourcing/infrastructure/eventplayer.py", line 42, in mutate
    return event.__mutate__(initial)
  File "/Users/admin/.local/share/virtualenvs/eventsourcing-ADotesgZ/lib/python3.7/site-packages/eventsourcing/domain/model/entity.py", line 187, in __mutate__
    obj = super(EntityWithHashchain.Event, self).__mutate__(obj)
  File "/Users/admin/.local/share/virtualenvs/eventsourcing-ADotesgZ/lib/python3.7/site-packages/eventsourcing/domain/model/events.py", line 162, in __mutate__
    self.__check_hash__()
  File "/Users/admin/.local/share/virtualenvs/eventsourcing-ADotesgZ/lib/python3.7/site-packages/eventsourcing/domain/model/events.py", line 139, in __check_hash__
    raise EventHashError()
eventsourcing.exceptions.EventHashError
```

It doesn't _appear_ to be a dataclasses issue. I noticed that the problem is no longer present if you add an intermediate save between the first and second command too:

```diff
  if __name__ == "__main__":
      with SQLAlchemyApplication(persist_event_type=Report.Event) as app:
          report = Report.__create__(name="my report")
          report.add_row(datasource_id="e1b2b779-192f-40a4-9dc1-46348e40fc95")
  
+         report.__save__()
  
          rows = list(report.rows.values())
          first_row_id = rows[0].id
          report.override_value(row_id=first_row_id, column=3, value="1500")
  
          report.__save__()
          assert report.id in app.repository
```

The full stack

**Comment by johnbywater** [comment]
@AlanFoster it's quite strange that the `__save__()` has an effect. My feeling is that the event hashing is probably indicating that the objects that the aggregate events have when they are reconstructed in the repository aren't quite the same as the objects that the aggregate events have when they are originally hash chained (ie when they are triggered)....

I just spent a few minutes debugging the hashing. The 'overrides' dict is getting passed around by reference, when it is really acting as a value object. So if you `.copy()` the event attribute rather than assigning it, then you can mutate it without also changing the event and tripping the event hashing. See the last line for the change that makes your program exit normally.

```
    class RowAdded(AggregateRoot.Event):
        @property
        def datasource_id(self):
            return self.__dict__["datasource_id"]

        @property
        def overrides(self):
            return self.__dict__["overrides"]

        def mutate(self, obj):
            obj.rows[self.id] = Row(
                id=self.id, datasource_id=self.datasource_id, overrides=self.overrides.copy()
            )
```

I suppose the reason the additional call to `__save__()` made it "work" is because then pending events are persisted and then go out of scope, fixing the record of the RowAdded domain event to have an empty dict, which is how it was when the state was hashed. And otherwise the RowAdded event is hanging around and keeping its reference to the dict waiting to get messed up when the overrides dict is given a value. And when it is persisted after its dict gets messed up by the ValueOverridden mutator adding a value to the dict, the resulting event record has a serialisation of a non-empty dict, and a hash for an event with an empty dict, and so when the hash is checked, an exception is correctly raised.

I hope that helps :-)

**Comment by johnbywater** [comment]
I think the better improvement would be not to trigger `RowAdded` with an `overrides` dict, but instead construct the dict that the aggregate has in the event's mutator.

So perhaps:

```
class Report(AggregateRoot):
    def add_row(self, datasource_id=None):
        self.__trigger_event__(
            Report.RowAdded, id=str(uuid4()), datasource_id=datasource_id
        )
```

with

```
    class RowAdded(AggregateRoot.Event):
        def mutate(self, obj):
            obj.rows[self.id] = Row(
                id=self.id, datasource_id=self.datasource_id, overrides={}
            )
```

would be slightly better?

**Comment by johnbywater** [comment]
One more thing to watch out for, something which I feel is slightly deficient: if you use integer values for dict keys, as you do in your program, then you should be aware that they get converted to strings by JSON (at least the JSON module used by the library at the moment, which is the core Python json implementation) so when you look at a domain event object that has been reconstructed, then it can have string dict keys instead of integer dict keys. Then if you use these keys in a mutator to set values on an aggregate, and later try get values with integer keys, the value will appear to be missing. If you want to avoid this, then just make sure you don't use integer dict keys in the domain events, or just make sure than you always convert to integers in the mutator. I've got no idea why the json module works this way.

**Comment by AlanFoster** [comment]
Thank you for looking into this! That's helped clear up everything for me, thanks very much :+1:
