### ISSUE TITLE
Why repository does not found entity_id ?

### ISSUE THREAD

**Issue by JeanDeuns** [johnbywater/eventsourcing#182]
Hello,

I'm trying to work with eventsourcing library and for the simple example : 

```python
class Ingredient(AggregateRoot):
    class Event(AggregateRoot.Event):
        pass

    @classmethod
    def create(cls, name: str):
        return cls.__create__(name=name)

    class Created(Event, AggregateRoot.Created):
        pass

    def __init__(self, name: str, **kwargs):
        super().__init__(**kwargs)

        self.name = name

    def __repr__(self):
        return f"<Ingredient (id={self.id} name={self.name}) object at {hex(id(self))}>"


class Ingredients(ProcessApplication):
    @applicationpolicy
    def policy(self, repository, event):
        pass

    @staticmethod
    def create_ingredient(name: str):
        return Ingredient.create(name)
```

When i try to execute the following code from a runner: 

```python
with SingleThreadedRunner(system, infrastructure_class=PopoApplication) as runner:
    ingredient = runner.system.ingredients.create_ingredient(name="Test")
    print(ingredient.id in runner.system.ingredients.repository)
```

the print returns "False" (the ingredient is not persisted ?)
where i'm doing something wrong ?

**Comment by JeanDeuns** [comment]
@johnbywater ?

**Comment by johnbywater** [comment]
Hey @JeanDeuns! Thanks for opening an issue. I'm sorry, I only just saw it.

What you did looks really good! Well done for getting so far with it. There were two things that you missed:

1. The factory method `create_ingredient()` doesn't call `__save__()` on the new aggregate before it returns it to the caller, so that the aggregate's pending events will actually be published.

2. Also you need to set `persist_event_type = Ingredient.Event` on the application class so that events of that aggregate are stored in that application when they are published.

The following code is working program that has these changes included. It prints `True` and exits normally. 

```
from eventsourcing.application.decorators import applicationpolicy
from eventsourcing.application.popo import PopoApplication
from eventsourcing.application.process import ProcessApplication
from eventsourcing.application.system import SingleThreadedRunner, System
from eventsourcing.domain.model.aggregate import AggregateRoot


class Ingredient(AggregateRoot):
    class Event(AggregateRoot.Event):
        pass

    @classmethod
    def create(cls, name: str):
        return cls.__create__(name=name)

    class Created(Event, AggregateRoot.Created):
        pass

    def __init__(self, name: str, **kwargs):
        super().__init__(**kwargs)

        self.name = name

    def __repr__(self):
        return f"<Ingredient (id={self.id} name={self.name}) object at {hex(id(self))}>"


class Ingredients(ProcessApplication):
    persist_event_type = Ingredient.Event

    @applicationpolicy
    def policy(self, repository, event):
        pass

    @staticmethod
    def create_ingredient(name: str):
        ingredient = Ingredient.create(name)
        ingredient.__save__()
        return ingredient


if __name__ == '__main__':

    system = System(Ingredients | Ingredients)

    with SingleThreadedRunner(system, infrastructure_class=PopoApplication) as runner:
        ingredient = runner.system.ingredients.create_ingredient(name="Test")
        print(ingredient.id in runner.system.ingredients.repository)
```

**Comment by johnbywater** [comment]
Please note, a `ProcessApplication` is a `SimpleApplication` and so can be used directly.

For example, rather than composing a system with one process application as I did above, you can directly mix-in the POPO infrastructure class into your infrastructure-free process application class, and instantiate and use the resulting application object:

```
if __name__ == '__main__':

    with Ingredients.mixin(PopoApplication)() as app:
        ingredient = app.create_ingredient(name="Test")
        print(ingredient.id in app.repository)
```

But of course if you are building up a system with more than one application, you are already on the right lines. Hope that helps! Feel free to ask more questions if and when you have them...

**Comment by JeanDeuns** [comment]
It works now, thank you.
You did a great work !

I will open other issues if I have others questions.

Note: https://eventsourcing.readthedocs.io/en/stable/topics/process.html#processes is not up to date :)

**Comment by johnbywater** [comment]
@JeanDeuns I think it's up to date? There's a small difference between the code that you linked to and the code you wrote. The "general rule" is that the `__save__()` method should be called on new or changed aggregates, except when they are created or updated within a process application policy (so that the domain events can be persisted atomically with the tracking and notification information). In particular, in that bit of the documentation, there is a command method on the Commands process application which does call `__save__()``. The other applications create and update aggregates with their process application policy, and so correctly do not call `__save__()`. It's a subtle aspect perhaps, but it reflects the atomicity of the recording. `__save__()` is atomic only for the new domain events of a single aggregate. Hope that helps :-)
