### ISSUE TITLE
Googling for event-sourcing and django and found this. Does this work well with Django 2.2?

### ISSUE THREAD

**Issue by simkimsia** [johnbywater/eventsourcing#199]
Hi there, 

I stumbled uppon this after googling for "Django" "event sourcing" 

Does this work well with Django 2.2?

I did find this https://eventsourcing.readthedocs.io/en/stable/ref/infrastructure.html#django though i was wondering if there's any  written docs with examples on how to use it within Django

The slack link is dead in this https://eventsourcing.readthedocs.io/en/stable/topics/support.html#community-support so I asked my question here. 

Thank you

**Comment by johnbywater** [comment]
@simkimsia Thanks for your interest in this project! Well done for finding a way in to the Slack workspace :-). The new invitation link to the Slack workspace is in the develop branch, but I didn't make a release yet, so it's not yet on the master branch unfortunately.
https://eventsourcing.readthedocs.io/en/latest/topics/support.html#community-support

The master branch setup.py shows the stable version of the library (the version that's released on PyPI) is working as tested with Django v2.2.
https://github.com/johnbywater/eventsourcing/blob/master/setup.py#L25

There are various parts of the documentation that describe how to use the library with Django. There's an example Django project in the library, which you can look at the to see how it can work. There is a DjangoApplication class which you will need to use.

And there is a sample Django project which somebody sent me, which has the particular distinction that it uses a custom Django app with custom model classes for storing events. This isn't on GitHub yet, but I can send it to you. The more convenient alternative of directly including the library's Django infrastructure module in "INSTALLED_APPS" setups up a table for every Django model in the library. Which isn't problematic, but gives you more tables than you need, and is avoidable by importing or copying only the model classes you actually want to use. You can to run migrations, and create the migrations if you make your own Django app. This should be familiar and straightforward for people familiar with Django, so if you get stuck, please just ask.

**Comment by Skyross** [comment]
@johnbywater Thank you for the great package. 

What do you think about allowing have a separate infrastructure for each Django application in the Django project? It would be good to use a separate set of tables for each event-sourced Django application. Split the legacy project/system into the small applications that can be easily extracted to the dedicates (micro-)services after proving the working state inside the monolithic codebase is the main scenario for this kind of usage I'm asking for. Separate tables will be easier to drop than cleaning common tables after moving from monolith to dedicated services for each application.

Or you have other thoughts about "the right way" for your library for this usecase?

Thank you.

**Comment by johnbywater** [comment]
Thanks @Skyross. I'm open to suggestions. The Django project in the library is primarily just a demonstration that it's possible to use the library with Django. But if you think it would be better to make some changes to it, then I'm open to your suggestions. I imagined that people would want to just create their own Django project, and perhaps even define their own models, in their own apps, according to their own preferences. But if it's more convenient to import from things in the library, and making changes to the library would facilitate that, then let's talk about it. So long as the tests pass, and it's not greatly complicated to the point where in total there is too much to maintain, I don't mind :-)

Having said that, I suppose I feel obliged to maintain backwards compatibility in things that are documented, so since the Django project in the library isn't documented, I don't worry so much about making changes to it, and about breaking other people's code. At the moment, it's more like a part of the test suite? So if people start depending on it, perhaps it should be documented?

At this point, I'm wondering whether it would be better to document how to make something that's independent of the library? It's possible to define model classes and use them.

I suppose it would be best, as a first move, to identify exactly what the use case is that you would like to support? I suppose I'm not exactly so clear about that. Do you mean that using the library Django model classes leads to all the ones in the library causing tables in the database, and it would be better to change the library so that only the ones used in an application are defined? If so, I would strongly support that. And if you can suggest changes that would make that happen, that would be amazing. If you wanted to talk about it further, let's do that. :-)

**Comment by Skyross** [comment]
@johnbywater Thank you for your answer. 

> Do you mean that using the library Django model classes leads to all the ones in the library causing tables in the database, and it would be better to change the library so that only the ones used in an application are defined?

Yes, the current approach at the library is perfect for small Django projects where the project contains one-two applications that can be complicated alike spaghetti and that a not a big problem.

For now, I aimed to split some parts of legacy system with dozens of applications that had coupled code. Some applications are good to be implemented with event-sourcing (some of them already event-sourced at a very basic and naive way). The plan for each application is about:
- cut dependencies to other domains: made them referencing each other via UUID only, disable related managers too
- implement an event-sourcing application that will copycat existed commands for existed entities but saving the events (fulfill the set of required events until objects states doesn't match)
- extract applications to dedicated services that connected through messaging transport

So, ideally, I'll want to see a couple of independent eventsourced application in the shared repository codebase. One of the options, I think, can be implemented via dedicated databases for each application and custom [database routing](https://docs.djangoproject.com/en/2.2/topics/db/multi-db/#topics-db-multi-db-routing) without any need to change the library code.

I will look into the current implementation withing the Django infrastructure and will provide some approach (code or PR) for your review.

**Comment by johnbywater** [comment]
Sounds really interesting! And I look forward to seeing what you do.

Just two points:

1. The actual Django project is really an artefact of the test suite, so please feel free to copy it, but perhaps don't write code that depends on it? I'm not sure if that's what you are thinking, but if not, just ignore this point.
2. Running more than one application and having them use separate databases might benefit from having better support for reading from environment variables. Perhaps reading "APPLICATION_NAME_DB_URI" if available, and then falling back onto "DB_URI" otherwise. This is something I have had in mind, but just haven't done so far. That way, you can still run the different applications in the same Python process, and have them operate from different databases. However, please also note that some of the runners are coded to pull event notifications directly from the database, with different applications having their own name space in the same stored events table, so this is an area that could perhaps be improved, so that the event notifications are pulled from the upstream database (or from the upstream application).
3. The Django models for storing events defined in the library can certainly be used, but if you aren't careful it will create a table for each model that's defined in the models module. This default is convenient, and it demonstrates the library works with Django ORM, but there are perhaps more optimal model definitions from a Django coding point of view, and also perhaps from a performance point of view. Do feel free to play around. Although the defaults work and are a convenient way to go, the library is hopefully a good jumping of point for playing around and finding something that suits your actual purposes. I've already spent quite a lot of time playing around with this, and this code is being used in production in various places, so the convenient defaults aren't so bad. But I'm sure you could find different ways of doing things, and you might prefer alternative arrangements.
4. I would be careful about propagating state by only pushing events to messaging infrastructure. If you are going to push the actual events, then it's perhaps wise to allow for "falling back" onto pulling messages when they aren't received in order, or are missing, so that "downstream" can count along the sequence. Also, when pushing messages, it's important not to overload the downstream application by sending more than it can handle. Messaging infrastructure obviously can help with this, to buffer things. But the "reactive" patterns, with "back pressure" are applicable here, and they aren't implemented in the library (I'm not sure if they are really in the scope of "event sourcing as persistence mechanism" but they are certainly adjacent). Pulling avoids all of these difficulties. Worth remembering that pushing an empty notification and setting a flag that shows something exists to be pulled, and then pulling ahead of processing, mostly eliminates the latency/intensity trade-off of polling for new events to pull. In the few experiments I've done with this, I've only achieved very small marginal improvements by pushing the actual events (see the options for running the Ray runner for details).

Good luck! :-)
