### ISSUE TITLE
event from constructor breaks object reconstruction

### ISSUE THREAD

**Issue by mwri** [johnbywater/eventsourcing#215]
This adaptation created by pasting bits from the quick start works:

```python
import os
os.environ['DB_URI'] = 'sqlite:///:memory:'
from eventsourcing.application.sqlalchemy import SQLAlchemyApplication
from eventsourcing.domain.model.aggregate import AggregateRoot
from eventsourcing.domain.model.decorators import attribute

class World(AggregateRoot):
    def __init__(self, **kwargs):
        super(World, self).__init__(**kwargs)
        self._history = []

    @property
    def history(self):
        return tuple(self._history)

    def make_it_so(self, something):
        self.__trigger_event__(World.SomethingHappened, what=something)

    class SomethingHappened(AggregateRoot.Event):
        def mutate(self, obj):
            obj._history.append(self.what)

# Construct simple application (used here as a context manager).
with SQLAlchemyApplication(persist_event_type=World.Event) as app:
    world = World.__create__()
    world.make_it_so('dinosaurs')
    print('new ID ' + str(world.id) + ' version ' + str(world.__version__) + ' history ' + repr(world.history))
    world.__save__()

    copy = app.repository[world.id]
    assert copy.history[0] == 'dinosaurs'
```

This one where I trigger an event from the constructor does not:

```python
import os
os.environ['DB_URI'] = 'sqlite:///:memory:'
from eventsourcing.application.sqlalchemy import SQLAlchemyApplication
from eventsourcing.domain.model.aggregate import AggregateRoot
from eventsourcing.domain.model.decorators import attribute

class World(AggregateRoot):
    def __init__(self, make_it_start_with=None, **kwargs):
        super(World, self).__init__(**kwargs)
        self._history = []
        if make_it_start_with != None:
            self.make_it_so(make_it_start_with)

    @property
    def history(self):
        return tuple(self._history)

    def make_it_so(self, something):
        self.__trigger_event__(World.SomethingHappened, what=something)

    class SomethingHappened(AggregateRoot.Event):
        def mutate(self, obj):
            obj._history.append(self.what)

# Construct simple application (used here as a context manager).
with SQLAlchemyApplication(persist_event_type=World.Event) as app:
    world = World.__create__(make_it_start_with='dinosaurs')
    print('new ID ' + str(world.id) + ' version ' + str(world.__version__) + ' history ' + repr(world.history))
    world.__save__()

    copy = app.repository[world.id]
    assert copy.history[0] == 'dinosaurs'
```

They create the same object, but in the DB the second one writes the object event before the object create, so retrieving the object then fails:

```sh
(venv) mjw@hari:~/dev/pyes2$ python3 quickstart_ok.py 
new ID f5c13603-7d73-4506-bf8a-d2e829061f0d version 1 history ('dinosaurs',)
(venv) mjw@hari:~/dev/pyes2$ python3 quickstart_bad.py 
new ID 168d133c-309f-4f7f-9853-b71f4c6ee2d5 version 1 history ('dinosaurs',)
Traceback (most recent call last):
  File "quickstart_bad.py", line 31, in <module>
    copy = app.repository[world.id]
  File "/home/mjw/dev/pyes2/venv/lib/python3.8/site-packages/eventsourcing/infrastructure/eventsourcedrepository.py", line 99, in __getitem__
    entity = self.get_entity(entity_id)
  File "/home/mjw/dev/pyes2/venv/lib/python3.8/site-packages/eventsourcing/infrastructure/eventsourcedrepository.py", line 144, in get_entity
    return self.get_and_project_events(
  File "/home/mjw/dev/pyes2/venv/lib/python3.8/site-packages/eventsourcing/infrastructure/eventsourcedrepository.py", line 200, in get_and_project_events
    return self.project_events(initial_state, domain_events)
  File "/home/mjw/dev/pyes2/venv/lib/python3.8/site-packages/eventsourcing/infrastructure/eventsourcedrepository.py", line 217, in project_events
    return reduce(self._mutator_func, domain_events, initial_state)
  File "/home/mjw/dev/pyes2/venv/lib/python3.8/site-packages/eventsourcing/infrastructure/eventsourcedrepository.py", line 233, in mutate
    event.__check_obj__(initial)
  File "/home/mjw/dev/pyes2/venv/lib/python3.8/site-packages/eventsourcing/domain/model/entity.py", line 354, in __check_obj__
    super(EntityWithHashchain.Event, self).__check_obj__(obj)
  File "/home/mjw/dev/pyes2/venv/lib/python3.8/site-packages/eventsourcing/domain/model/entity.py", line 474, in __check_obj__
    raise OriginatorVersionError(
eventsourcing.exceptions.OriginatorVersionError: Event takes entity to version 1, but entity is currently at version 1. Event type: 'SomethingHappened', entity type: 'World', entity ID: '168d133c-309f-4f7f-9853-b71f4c6ee2d5'
(venv) mjw@hari:~/dev/pyes2$ 
```

Versions:

```text
certifi==2020.6.20
chardet==3.0.4
eventsourcing==8.2.3
idna==2.10
pycryptodome==3.9.8
python-dateutil==2.8.1
readerwriterlock==1.0.7
requests==2.23.0
six==1.15.0
SQLAlchemy==1.3.19
SQLAlchemy-Utils==0.36.8
typing-extensions==3.7.4.3
urllib3==1.25.10
```

**Comment by johnbywater** [comment]
Yes, you can't do that because the constructor is not the factory. The constructor is used to construct and reconstruct the aggregate object from a "created" event. So it's properly part of the projection of the aggregates's domain events into the aggregate object. As such no domain events should be triggered in the constructor. You should just trigger domain events within the aggregate factory method, or with the aggregate object command methods. Hope that helps!

**Comment by johnbywater** [comment]
Thanks for the question, and your interest in the project! If you need any further guidance, please feel free to reopen the issue.

Perhaps if you are wanting to always start with a history, then you could extend the factory method by triggering a second event? That would allow clients to call the factory method, and get an aggregate with one item in the history.

**Comment by mwri** [comment]
Yes, there are ways of dealing with it, or wrapping it away, it just seemed like it should work, thanks.
I think it's maybe just a bit odd/unideal that you can construct the aggregate this way successfully, but that it results in a corrupted event log.

**Comment by johnbywater** [comment]
Yes, I can see that something remains to be desired, from a usability point of view. Somehow guarding against triggering events from within the aggregate projection would make this much clearer. You aren't the first to do this, and it would be better if the library somehow reported this as a programming error.

However, having said that, I think the problem is not not that the event log is getting corrupted: there are only two events in the event log. What's happening is that, when replaying the two stored events, a second "something happened" event is triggered after the "created" event is applied, which evolves the state of the aggregate object past the state in which the first "something happened" event was triggered, and so when the first "something happened" event is applied during the replaying of the two stored events, the aggregate isn't any longer in a valid state because it's version number has been increased by the triggering of the second "something happened" event during the replaying of the "created" event.

If the OriginatorVersionError wasn't raised (if this check wasn't made), the event store would raise a conflict error when the aggregate is saved, because it would try to save the second "something happened" event in a position in the aggregate sequence ("originator_version == 1") that is already occupied. So the exception you are seeing is an early sign that something is wrong, and there isn't even an attempt to corrupt the event log because of this check. But it would be better if the library guarded against triggering events within any function that contributes to the aggregate's projection of its domain events.

**Comment by mwri** [comment]
I accept it as a use error, and even actually a bit wrong headed when you get really get very far, and I agree guarding against event trigger as you say would be best.

Is what you say about the event log not being corrupted true though? I don't want to nit pick, it's perhaps not hugely important given acceptance and agreement above, but the reason I referred to the event log as being corrupted is that I observed post creation and persistence of the aggregate that the (persisted) event log is thus:

```text
sqlalchemyapplication|oи��M��;#T�|1|0|1|__main__#World.SomethingHappened|{"originator_id":{"UUID":"6fd0b8b41de44da78f3b231519540295"},"originator_version":1,"what":"dinosaurs","__previous_hash__":"","timestamp":{"__decimal__":"1598441918.306160"},"__event_topic__":"__main__#World.SomethingHappened","__event_hash_method_name__":"__hash_object_v2__","__event_hash__":"c587a88bd21256e7de6a732876994ab7fd5bc7f00e5e74f4ebfe3b98c1cabb8c"}|
sqlalchemyapplication|oи��M��;#T�|0|0|2|eventsourcing.domain.model.aggregate#AggregateRoot.Created|{"originator_id":{"UUID":"6fd0b8b41de44da78f3b231519540295"},"originator_version":0,"originator_topic":"__main__#World","make_it_start_with":"dinosaurs","__previous_hash__":"","timestamp":{"__decimal__":"1598441918.305533"},"__event_topic__":"eventsourcing.domain.model.aggregate#AggregateRoot.Created","__event_hash_method_name__":"__hash_object_v2__","__event_hash__":"603aff6218f03a097c72fdd22cf72c4c675679086d154fd0b44b5da3aa46695a"}|
```

Obviously the persistence details are not part of the library interface, but I deemed these to be in the wrong order.

If one attempts to replay and recreate the aggregate after removing the event trigger from the aggregate constructor it fails thus:

```sh
(venv) mjw@hari:~/dev/pyes2$ python3 quickstart_bad2.py 
Traceback (most recent call last):
  File "quickstart_bad2.py", line 31, in <module>
    copy = app.repository.get_entity('6fd0b8b4-1de4-4da7-8f3b-231519540295')
  File "/home/mjw/dev/pyes2/venv/lib/python3.8/site-packages/eventsourcing/infrastructure/eventsourcedrepository.py", line 144, in get_entity
    return self.get_and_project_events(
  File "/home/mjw/dev/pyes2/venv/lib/python3.8/site-packages/eventsourcing/infrastructure/eventsourcedrepository.py", line 200, in get_and_project_events
    return self.project_events(initial_state, domain_events)
  File "/home/mjw/dev/pyes2/venv/lib/python3.8/site-packages/eventsourcing/infrastructure/eventsourcedrepository.py", line 217, in project_events
    return reduce(self._mutator_func, domain_events, initial_state)
  File "/home/mjw/dev/pyes2/venv/lib/python3.8/site-packages/eventsourcing/infrastructure/eventsourcedrepository.py", line 233, in mutate
    event.__check_obj__(initial)
  File "/home/mjw/dev/pyes2/venv/lib/python3.8/site-packages/eventsourcing/domain/model/entity.py", line 358, in __check_obj__
    raise HeadHashError(obj.id, obj.__head__, type(self))
eventsourcing.exceptions.HeadHashError: (UUID('6fd0b8b4-1de4-4da7-8f3b-231519540295'), '603aff6218f03a097c72fdd22cf72c4c675679086d154fd0b44b5da3aa46695a', <class '__main__.World.SomethingHappened'>)
(venv) mjw@hari:~/dev/pyes2$ 
```

That's running the following code now, the second time, where I have hard coded the ID created by the previous invocation, commented out the bad event trigger in the constructor and the irrelevant creation of `world`:

```python
import os
os.environ['DB_URI'] = 'sqlite:///./db9.sqlite'
from eventsourcing.application.sqlalchemy import SQLAlchemyApplication
from eventsourcing.domain.model.aggregate import AggregateRoot
from eventsourcing.domain.model.decorators import attribute

class World(AggregateRoot):
    def __init__(self, make_it_start_with=None, **kwargs):
        super(World, self).__init__(**kwargs)
        self._history = []
        # if make_it_start_with != None:
        #     self.make_it_so(make_it_start_with)

    @property
    def history(self):
        return tuple(self._history)

    def make_it_so(self, something):
        self.__trigger_event__(World.SomethingHappened, what=something)

    class SomethingHappened(AggregateRoot.Event):
        def mutate(self, obj):
            obj._history.append(self.what)

# Construct simple application (used here as a context manager).
with SQLAlchemyApplication(persist_event_type=World.Event) as app:
    # world = World.__create__(make_it_start_with='dinosaurs')
    # print('new ID ' + str(world.id) + ' version ' + str(world.__version__) + ' history ' + repr(world.history))
    # world.__save__()

    copy = app.repository.get_entity('6fd0b8b4-1de4-4da7-8f3b-231519540295')
    assert copy.history[0] == 'dinosaurs'
```

Listing the events via `app.event_store.list_events(world.id)` (after creating it with the trigger in the constructor) does list events in the expected order; the create before the "dinosaurs" event.

**Comment by johnbywater** [comment]
That's interesting. That's because the second event is being triggered before the first event has completed mutating the aggregate, which is a consequence of triggering the event within the projection. Basically, the "head hash" of the aggregate object is assigned from the created event to the aggregate object after the aggregate constructor has been called. Since the second event is triggered within the constructor the head hash hasn't been set on the aggregate object. That results in the second event being triggered with a "previous hash" that isn't the head hash that results from projecting the created event into the aggregate object. When the two events are replayed in the "repaired" code, it doesn't get snagged on the version error because the second event isn't being triggered twice, but it does get snagged on the hash chain error, because now the hash of the "created" event is set on the aggregate as its head hash, and this isn't equal to the "previous hash" included in the second event.

**Comment by johnbywater** [comment]
I've been looking into guarding against this, but I can easily see how to completely guard against this triggering of events from within functions that contribute to the projection of the domain events of an aggregate to the aggregate object itself. But let's keep thinking about it? It would be nice to have a `ProgrammingError` raised when an attempt is made to trigger an event during the projection of events into the state of the aggregate. Maybe there's a neat way to do it, but I can't see what it is just now.

**Comment by johnbywater** [comment]
By the way, @mwri, please do feel free to join the Slack workspace, if you haven't already!

**Comment by johnbywater** [comment]
@mwri We're discussing how to improve the usability with respect to this concern.
https://app.slack.com/client/T627DFUV7/C627DFVJM/thread/C627DFVJM-1598455731.006800

By the way, if you are in London and want to meet up, drop me a line!
