### ISSUE TITLE
Query all aggregates

### ISSUE THREAD

**Issue by sebaacuna** [johnbywater/eventsourcing#226]
After checking the documentation I’m not sure what the recommended eay of querying for all aggregates would be.

I’m looking for a way to be able implement something like:

```python
def get_all_things() -> List[UUID]:
```

Where I’d have a `Thing` aggregate.

Some context; I’m adding a querying capabilities to my Application using `whoosh` (inverted index) but I’d to rebuild the index under certain scenarios so I’d like to get all aggregate ids, fetch them from the repository and index each in turn.

**Comment by sebaacuna** [comment]
What I ended up doing was traversing the `application.log`, something like this:

```python3
    def get_changed_aggregates_since(self: Application) -> Iterable[UUID]:
        def sections():
            section_id = '1,100'

            while section_id is not None:
                section = self.log[section_id]
                yield section
                section_id = section.next_id

        def agg_ids():
            for section in sections(bookmark):
                for item in section.items:
                    yield item.originator_id
       
       return list(set(agg_ids()))
```

Still not 100% sure this would be the best/recommended way to accomplish the task...

**Comment by johnbywater** [comment]
Thanks for asking your question, and posting your solution. As you can see there isn't actually a method to list out all the IDs, but perhaps one should be added.

Perhaps you have seen already, but if you haven't please note that all the recorders in the library do have an index from which the aggregate IDs could be obtained. These indexes are used to get the aggregate events, but they will work to select the aggregate IDs well enough. Querying for the aggregate IDs isn't presented as query method in the base class for aggregate recorders `eventsourcing.persistence.AggregateRecorder` nor implemented in the concrete classes, but it perhaps could be. Nevertheless, you could implement something in your own application code that reads from the recorder or recorders you are using. If you use more than one type of recorders, you could make this code conditional upon the types recorders used by your application, and add support for whichever recorders you are using, so that it works with different ones at different times.

I would think the best way to use the log is to incrementally update the index from the domain events. Following the log of an application will allow you to propagate the state of the application incrementally as things happen in that application. Processing the event notifications will allow the state to be projected into an index or anything else progressively. The process application class demonstrates a little framework for doing this: using a log reader to iterate over new event notifications, getting an aggregate event object from an event notification, then processing the aggregate event through a policy, and finally recording the results atomically with a tracking record from which the reader can be positioned to get the next unprocessed events. You can replicate the code to make variants of this process, or use the process application class itself.

It's the need to progressively propagate and process the state of an application still being used and still recording new events which leads to wanting to follow the application's log. Trying to read out all the aggregates is an appealing way to process the state of an application that isn't continuing to generate events. But when there are new aggregate events still being generated, repeatedly getting all the aggregates will gradually become a longer and longer process, and hence gradually the latency (and wastefulness of getting and processing things that have already been seen) will increase.

If you need any more help or guidance in your using the library, please don't hesitate to ask more questions.

Thanks for using the library, and good luck with your work!

**Comment by sebaacuna** [comment]
Hi John, thanks for your thorough reply. What you mention is exactly where I'm trying to get to; being able to follow the events and maintain my search index up to date (and eventually other read models).

I'll take a look at the process app and how the policy is implemented. I'm still wrapping my head around DDD and event sourcing in general. I've found your eventsourcing library extremely helpful to navigate the concepts in a tangible way and I'm really liking the general feel of it.

Kudos John and thanks again!
