### ISSUE TITLE
storage layer abstraction propose

### ISSUE THREAD

**Issue by renou** [johnbywater/eventsourcing#27]
Hi John!

I'm working on a new storage layer for the library using Django ORM for easy django integration. However, I find it hard to do in the current setup.

Currently when we save a domain event we go through DomainEvent -> StoredEvent -> DB implementation. it works great if all DB implementation uses schema that follows StoredEvent schema. However, if I'd like to have a different schema I need to somehow "deserialize" back to domain event since many DomainEvent fields are combined into one in StoredEvent.

My proposal is to move the abstraction a layer up from StoredEventRepository to EventStore(and maybe rename "EventStore" to "EventRepo" to follow the repo pattern). And the developer can have the flexibility of transcode the Domain event to whatever schema they like. And the downstream can be the default implementation of the repo.

The lib works great in most cases as long as we use it as is and not caring about the actual storage. However, there are cases, we do care about how the data is stored. 

Let me know what you think, thank you!

Here is an example of the code I have to write to implement a different schema:
```python
    def write_version_and_event(self, new_stored_event, new_entity_version=None, max_retries=3, artificial_failure_rate=0):
        domain_event = self.deserialize(new_stored_event) # :(
        dt = datetime.datetime.fromtimestamp(timestamp_from_uuid(new_stored_event.event_id))
        Event.objects.create(
            event_id=domain_event.event_id,
            event_type=type(domain_event).__name__,
            event_data=new_stored_event.event_attrs,
            aggregate_id=domain_event.entity_id,
            aggregate_type=id_prefix_from_event(domain_event),
            aggregate_version=new_entity_version,
            create_date=make_aware_if_needed(dt),
        )

# models.py
class Event(models.Model):
    event_id = models.CharField(max_length=255, primary_key=True)
    event_type = models.CharField(max_length=255)
    event_data = models.TextField()
    aggregate_id = models.CharField(max_length=255, db_index=True)
    aggregate_type = models.CharField(max_length=255)
    aggregate_version = models.IntegerField()
    metadata = models.TextField()
    create_date = models.DateTimeField(db_index=True)

    class Meta:
        unique_together = ('aggregate_id', 'aggregate_version',)
```

I think the EventStore is a good line of abstraction. It takes in domain events on write and returns domain events on read.
Bo

**Comment by johnbywater** [comment]
Thanks for your proposal. I'll give it some thought. I suppose if I wanted to support a different persistence model across different backends, I would need to make a new StoredEvent namedtuple that has all the attribute values that will be persisted. I'd also need a new transcoder that uses that namedtuple. In #28 I just refactored the event store so that it has a transcoder constructor argument, instead of all the args that are eventually passed into the transcoder functions. I think you could accomplish what you are describing above by subclassing the Transcoder, and extending the serialize() method so that it returns the data you need for your Event class, perhaps with a new namedtuple. You could call the existing methods and then use the StoredEvent instance they return, along with the domain event, to make an instance of a namedtuple that has all the attributes needed by your Event class. Does that make sense for what you are trying to do with Django?

**Comment by johnbywater** [comment]
Also I was curious what it is that you care about that brings you to your new Event model? It would be possible to make something for the Django ORM that works in a similar way to the SQLAlchemy stored event repo. So I just wondered what your persistence model helps you achieve?

**Comment by johnbywater** [comment]
And the other thing I wanted to say about Django, is that it would possible to write a backend, or even just two query classes, that would allow a normal Django model to be persisted with the event sourcing library. That would mean a lot of the integrations you get with Django wouldn't be broken by introducing a completely new way of writing a model. But obviously when it comes to the Django model query syntax that effectively supports joins and other SQL-shaped queries, things would need quite a lot of thought. It should work out though, because there shouldn't be the impedance mismatch that makes ORMs difficult.

How have you been writing your Django project, have you been calling into an eventsourcing application from view classes?

**Comment by renou** [comment]
Hi John!
1. Oh, I see. It's not very obvious, may be some explicit abstraction would make it clear to developers?
2. The reason is we are having multiple backends of different languages of event sourced services. We use events for reactive inter-service communication through kafka. It's easier to have a common event "data structure" so that all service will understand it. And we have come up with a standard structure that we liked most described in the code I post above.
3. Yes, we are calling eventsourcing application from view classes. What's ur thought on that?

**Comment by johnbywater** [comment]
Hi Bo, I had another look at the snippet above. It seems you could get all the values you need directly from the 'new_stored_event' object, without deserialising it back into a domain event. Let me know if it works for you?

```
    def write_version_and_event(self, new_stored_event, new_entity_version=None, max_retries=3, artificial_failure_rate=0):
        dt = datetime.datetime.fromtimestamp(timestamp_from_uuid(new_stored_event.event_id)
        event_qualname = new_stored_event.event_topic.split('#')[1]
        if '.' in event_qualname:
            entity_class_name, event_class_name = event_qualname.split('.')
        else:
            # Some events are not part of an entity e.g. MessageLogged.
            event_class_name = event_qualname
            entity_class_name = ''
        Event.objects.create(
            event_id=new_stored_event.event_id,
            event_type=event_class_name,
            event_data=new_stored_event.event_attrs,
            aggregate_id=new_stored_event.event_attrs['entity_id'],
            aggregate_type=entity_class_name,
            aggregate_version=new_stored_event.event_attrs['entity_version'],
            create_date=make_aware_if_needed(dt),
        )
```

About calling an event sourcing application in Django view classes: I think it's perfect from a DDD point of view, in that the Web framework is clearly forming the interface layer. At the same time, I'm very aware that there are loads and loads of really useful, convenient, popular things that using the Django model brings - things that lots of developers know and miss very much when the Django model is taken away (e.g. the admin view). Although, I feel we don't necessarily want to have an API simply be a reflection a domain model. It is good to define the API entirely in the presentation layer, separate from the model. But if you need lots of CRUD views, without reflection, you have to write a lot of code.

So I don't think it's somehow lacking to write Django views that call an event sourcing model, I think that's a very nice architecture. But I do think there might somehow be an integration between Django models and an event sourcing application, so that you can perhaps define a typed model in a normal Django way. There are a few projects running along these lines, with nosql databases. There is the Django Cassandra Engine, which brings it's own 'Model' and 'Column' (not 'Field') classes (https://pypi.python.org/pypi/django-cassandra-engine/). There is also the Django-nonrel fork (http://django-nonrel.org/) but it's master branch is by now 8373 commits behind the Django project's master branch. An entire new backend could be written, but I think a quick way to do it is with a new query set class and set it on the model class: you can define a query set that behaves normally as a query set but intercepts the CRUD operations that would make database calls and does event sourcing application shaped things instead. I did it already successfully for one class in Django Cassandra Engine, which works in a similar way to the normal Django model. I didn't generalise it to work with all models, but I think that would be possible with a little bit of work. That's why I think it would be possible to do something interesting with the normal Django query set, but I didn't actually try that yet. Please don't let any of this make you hesitate about your current line of development. It's basically a possibility that would need a bit of work to fix up.

About the transcoder: I think it can help to make variations of the model, but there are several features that mean there are some constraints on how much it can be varied? The abstraction is more or less the StoredEvent type (a namedtuple): that's what a stored event repository makes durable (interface), the event store don't care how that is accomplished (implementation). The event store deals in terms of domain events, and has a transcoder which converts between domain events and stored events. These three parts could be merged into a single class, and databases could be adapted by subclassing the event store class. I just happened to separate these three things. I don't really know if it's better that having event store subclasses. It feels a bit more stable to just have one type of event store, with dependencies injected by constructor parameter. With that design, I can switch in a new stored event repo according to the database I am using. I can use whatever schema I want, constrained by the values carried by the stored event object and the queries required to retrieve the events. And when I want to serialise my event attributes in a special way, I can switch in a different transcoder. Hopefully it's a bit more obvious after the refactoring, but in any case, it would be great to have some fabulously illuminating documentation. I did recently revise the README a bit :)

John

**Comment by renou** [comment]
Hi John!

Thank you for your reply! I will read it again later. Right now I think I can do what I want by making a new Transcoder and a new StoredEvent Named Tuple.

I will have something like this:
Domain Event <-> EventStore <-> NewTranscoder <-> NewStoredEvent <-> NewStoredEventRepoUsingDjangoModel

It should work. However, as I mentioned in another issue. The implementation detail of  how stored_entity_id is constructed is leaking through layers. Right now, I have to do this:

```python

    def extract_aggregate_type_and_id(stored_entity_id):
        # have to do this to match lib's signatures
        # Survey::6deaca4c-d866-4b28-9878-8814a55a4688 => ('Survey', '6deaca4c-d866-4b28-9878-8814a55a4688')
        split_arr = stored_entity_id.split('::')
        return split_arr[0], split_arr[1]

```

**Comment by johnbywater** [comment]
Sorry for the long comment! Actually the method above won't work because the attrs are already JSON strings, so you can't look up the values as I wrote it above, without deserializing the JSON which you don't want to do - sorry about that! So yes, expand on what the included StoredEvent object carries by defining your own type, and extend the Transcoder so that you have something that can provide the values needed in your schema.

Regarding your method 'extract_aggregate_type_and_id': if that's in your transcoder, you will have access to the domain event object, and so you will be able to get the entity ID from the domain event itself. The entity type is a bit more tricky, you have to go by way of the qualname. You can also use the function 'id_prefix_from_event' (in transcoding.py) to get your "aggregate type" value from the domain event object. You can get the value by splitting the stored entity ID, or by splitting the event topic, but those two values are made by calling 'id_prefix_from_event' so you might as well call it directly, since you don't store the event topic. Thinking about it a bit more, your not storing the event topic suggests you will anyway need to write a transcoder that knows how your "aggregate type" and "event type" values are resolved to your domain event classes when deserializing an event. I guess, they could be in a predictable location, but if you've got those associations in code, then perhaps you could also use them to get the "aggregate type" and "event type" values when serializing an event?

**Comment by renou** [comment]
It works as long as I make myself a NewTranscoder so I can control the format of stored event. :) As far as stored_entity_id concerned, I'm gonna keep using it since too many places dependents on it, like event player, snapshotting. Works for me right now.

**Comment by johnbywater** [comment]
👍
