### ISSUE TITLE
Exclude unnecessary packages (tests, examples) from distribution

### ISSUE THREAD

**Issue by vmorugin** [johnbywater/eventsourcing#284]
When installing the `eventsourcing` package, unnecessary directories like `tests` and `examples` are included in the package by default. These folders are not required for production use and add extra size to the installation. 

To improve the package structure and reduce its size, please adjust the build configuration to exclude these directories from the default distribution.

**Steps to Reproduce**:
1. Install the package via pip:
   ```bash
   pip install eventsourcing
   ```
2. Observe that `tests` and `examples` folders are included in the installed package.

**Expected Behavior**:
Only the essential source files are included in the package, excluding `tests`, `examples`, and any other non-essential directories.

**Suggested Solution**:
Update the `MANIFEST.in` or setup configuration to exclude these unnecessary directories from the package.

**Environment**:
- Python version: 3.11
- eventsourcing version: 9.3.2

**Comment by johnbywater** [comment]
I just published version 9.3.4, which doesn't include the examples package, and also doesn't include most of the test cases.

The wheel for version 9.3.4 is 73.9 kB. It was 197.7 kB for version 9.3.3. So that's a reduction of more than 50%.

https://pypi.org/project/eventsourcing/9.3.3/#files
https://pypi.org/project/eventsourcing/9.3.4/#files

You will notice that there are is still an eventsourcing.tests package. It now contains only common test cases that are used by both the core persistence modules and the persistence module extension packages. I'm thinking about how this might be improved, but most things have been excluded and 9.3.4 is a step in the right direction.

Thanks again for raising this issue. I appreciate it.

**Comment by vmorugin** [comment]
Thank you for your responsiveness and improvements!
