### ISSUE TITLE
"Restoring an aggregate via event replay leads to history inconsistency"

### ISSUE THREAD

**Issue by Yaros75** [johnbywater/eventsourcing#285]
Hello, eventsourcing team!

My name is Yaroslav, and I’m exploring your library. I encountered an issue related to restoring aggregates from events and applying new events, which leads to inconsistencies in the aggregate’s history.

Situation:
Here’s a reproducible example:
```python

from eventsourcing.domain import Aggregate, event

class Dog(Aggregate):
    @event('Registered')
    def __init__(self, name):
        self.name = name
        self.tricks = []

    @event('TrickAdded')
    def add_trick(self, trick):
        self.tricks.append(trick)

def example_1():
    dog = Dog(name='Fido')
    events = dog.collect_events()

    # Restore state from events
    copy = None
    for e in events:
        copy = e.mutate(copy)

    # Direct reference to the original object
    cat = dog

    # Apply a new event to the original
    dog.add_trick(trick='roll over')

    # Print states
    print(dog.tricks)  # ['roll over']
    print(copy.tricks)  # []
    print(cat.tricks)  # ['roll over']

example_1()
```

Output:
```
Копировать код
['roll over']
[]
['roll over']
```

Problem Description:
I created an aggregate dog and restored its state to copy using events.
I then applied a new event to the original aggregate dog ("roll over").
copy retained the old state since it’s a separate object.
However, copy and dog share the same aggregate id.
If both objects are saved into the event store, the following happens:

The new event will be duplicated in the aggregate’s history.
This causes data inconsistency and breaks the integrity of the event history.
Question:
Is there a mechanism to prevent such situations? Can the library track restored aggregate instances with the same id? Or is this responsibility delegated to the developer?

**Comment by johnbywater** [comment]
Hi @Yaros75!

Thanks for exploring the library and posting this issue.

What's happening in this example is that the `events` you have collected has length `1`. There is just the created event. After replaying this event you get a copy of the aggregate in the state is was in before any tricks were added. Then you added a trick. That's why when you print the tricks at the end the reconstructed `copy` doesn't have any tricks but the original (`cat` and `dog`) have one trick.

> The new event will be duplicated in the aggregate’s history. This causes data inconsistency and breaks the integrity of the event history. Question: Is there a mechanism to prevent such situations?

In the persistence modules provided by this project, and also in specialist event store databases, there are uniqueness constraints that prevent duplicate events being recorded.

> Can the library track restored aggregate instances with the same id? Or is this responsibility delegated to the developer?

You would get a database integrity conflict error when trying to save in this case: (1) create and save an aggregate, (2) reconstruct two instances of the original aggregate, (3) save one, and then (4) save the other. You will get an error on step 4. Try it and see?

The library doesn't track which aggregates have been reconstructed for the purpose of avoiding recording duplicate events, because it wouldn't be possible to track this across separate Python interpreters.

```
from eventsourcing.application import Application
from eventsourcing.domain import Aggregate, event

class Dog(Aggregate):
    @event('Registered')
    def __init__(self, name):
        self.name = name
        self.tricks = []

    @event('TrickAdded')
    def add_trick(self, trick):
        self.tricks.append(trick)


def example_1():
    app = Application()
    dog = Dog(name='Fido')
    app.save(dog)

    copy1 = app.repository.get(dog.id)
    copy2 = app.repository.get(dog.id)

    copy1.add_trick(trick='roll over')
    app.save(copy1)

    copy2.add_trick(trick='lay down')
    app.save(copy2)

example_1()
```

You will get `eventsourcing.persistence.IntegrityError: Stored event already recorded`.
