### ISSUE TITLE
Snapshotting and mutator initial state

### ISSUE THREAD

**Issue by yarbelkgazia** [johnbywater/eventsourcing#58]
When I have snapshotting enabled, I need to set up a mutator for initial state of the replay:
https://github.com/johnbywater/eventsourcing/blob/v2.1.1/eventsourcing/infrastructure/eventplayer.py#L69

which is None.  with the default handler, you get an unsupported exception.  This should probably added into the docs as it is a per entity type handler

```

@example_mutator.register(type(None))
def example_none_mutator(event, _):
    """Due to the snapshotting - you need to return the class on
    empty"""
    return ExampleEntity
```

**Comment by yarbelkgazia** [comment]
Actually, I'm not sure on this:  I seem to get errors depending on if there are 1 or multiple events in the list, using this.

**Comment by johnbywater** [comment]
Not sure which class method you meant. Also I think it's correct that the snapshot events aren't supported by the mutator function.

On the develop branch, the ```ExampleApplication``` enables snapshotting by constructing a snapshot strategy, then passing it to the event sourced repository. That causes the repository to check for a snapshot before it gets all the events. And if there is a snapshot, it only gets the events that were applied after the snapshot was taken. It also uses older snapshots when getting an entity at a historical version. There are quite a few tests covering it.

```
        self.example_repo = ExampleRepository(
            event_store=self.version_entity_event_store,
            snapshot_strategy=self.snapshot_strategy,
        )
```

However, I had two issues with this code: firstly snapshots used timestamps not version numbers, and also there wasn't a snapshotting policy to automatically create snapshots.

So I just reworked the snapshotting. The snapshot records are now in a dedicated table. Snapshots use integers which correspond to event entity version attribute, rather than event timestamps. I added a section to the README file about using snapshots (will move it to the new docs when the code snippets in the new docs are covered with a test, with something like the test_readme.py). And in that new section added an example snapshotting policy that automatically takes a snapshot every five events.

The changes are in PR #60. Let me know what you think?

**Comment by yarbelk** [comment]
Yup, that is the method I was talking of - it switches the argument order from the `@singledispatch` - which needs `F(event:E, state:S) -> S` to `F'(state:S, event:E) -> S`, which is needed by `reduce`.  This took me a bit of time to catch, as its a rather subtle difference when you're just reading through the code.

I added some comments to PR #60 , I like the refactors: it feels cleaner.

Looking forward to the next release.

**Comment by johnbywater** [comment]
Just to link things up, there is now a page in the documentation about snapshotting, here:

http://eventsourcing.readthedocs.io/en/latest/topics/user_guide/snapshotting.html
