### ISSUE TITLE
Assumptions on type in persistance policy

### ISSUE THREAD

**Issue by yarbelkgazia** [johnbywater/eventsourcing#59]
When using the Combined Persistence policy, there are undocumented assumptions about what the class hierarchy of the events are.  This should probably be documented.

(If you haven't noticed, I'm adding notes for the documentation)

**Comment by johnbywater** [comment]
Agreed, although the distinction between time and integer sequenced events is described. The subscription predicate in the ```PersistencePolicy``` tests for the type it is given, so that other things are not handled. By having one policy for ```TimestampedEntityEvent``` and a second for ```VersionedEntityEvent```, the combined policy codes explicitly for persisting both those types of domain events. In #60 I added a third, for ```Snapshot```. Not sure if a "combined" policy is such a great thing to have in the library. Perhaps it would be better to factor it out.

**Comment by johnbywater** [comment]
I've removed the combined persistence policy entirely, so will close this issue.

I do think the event classes could usefully be documented, hopefully more will be written about them soon. Will be doing the aggregate roots and events next, so that may lead on to documenting all the event classes, perhaps as a reference rather than a user guide.
