### ISSUE TITLE
missing domain events

### ISSUE THREAD

**Issue by yarbelkgazia** [johnbywater/eventsourcing#89]
When trying to get all the entities in a repo, I have been seeing that several domain events were missing.  (version 2.1.1, cassandra)

the code in question is:

```
class FooRepo(EventSourcedRepo):
    ...
    def get_foo_entities(self):
        foos_created = filter(
                lambda x: isinstance(x, CreatedFoo),
                self.event_store.all_domain_events())
        return [self.get_entity(f.entity_id) for f in foos_created]
```

When investigating, the `event_store.all_domain_events()` was returning 27 events, while there are 32 in the cassandra table.

switching to filtering on unique `entity_ids` seems to give the correct  output:

```
def get_foo_entities(self):
        foo_ids = set(f.sequence_id for f in self.event_store.active_record_strategy.active_record_class.objects.value_list('s').distinct())
        return [self.get_entity(f) for f in foo_ids]
```

and getting the entity with `get_entity` for the missing events works correctly.

I have no idea why this is happening.  Also, as random rows seem to be missing from the all_items calls, I'm leery about using either of these methods.  (which is why I'm using the cassandra model class rather than all_items).

**Comment by johnbywater** [comment]
Thanks for raising the issue. For this whole project, I've been struggling to know how to get all the events in order from Cassandra, given the partition keys are laid down without order, and there are potentially too many things to get in one query without risking a timeout.

I think the bug you found is the method all_domain_events() in Cassandra uses a function that has a fixed limit of 10. So the missing events will be for entities that have more than 10 events. I guess you have a total of 5 events with entity version number >= 10. :(
https://github.com/johnbywater/eventsourcing/blob/develop/eventsourcing/infrastructure/cassandra/activerecords.py#L87

It is broken because the underlying "primary key token" that is used only selects the partition key (the sequence ID), not actually the full composite. So when it asks for the next one (the 'gt' arg) it skips to the next partition, having returned maximum 10 items from that sequence.

Having searched for a while, I've kinda concluded reluctantly that it is possible directly to get all the events in order from the Cassandra table. I think the best thing that can be done is to work through the distinct partition keys using the token method, but with with a limit of 1 rather than 10, in case there are more partition keys than can be returned in one query. That will lead to an unordered sequence of partitions, which can be used to get all the items in each partition. I guess that "distinct" query will have a default limit of 10000 items (?) so that it will never return more than 10000 partition keys, and if you increase the limit you risk getting timeouts.

The challenge with Cassandra, which will probably reveal itself eventually with an SQL DBMS, is dealing with the two constraints "the most that can returned in one query (otherwise you get a timeout)" and "the most that can fit in one partition (otherwise it runs real slow)" combined with the fact that the token ring is not ordered.

But we need the events in order to update projections of multiple aggregates, especially remote contexts. That's why I've been trying to figure out how a good way to store references to events either in a single time bucketed log (each time bucket uses its own partition) or with an integer sequenced log that spans multiple partitions (the BigArray class, on the develop branch).

The advantage of timestamps is throughput, you don't need to figure out which is the next number. And with TimeUUIDs you can assume they won't collide, so you can just write lots of them in parallel. However the trouble with timestamps is that they may get out of logical sequence, if e.g. a clock on one node is different from the clock on another node, which is always true to some extent, then just looking at timestamps could give you the wrong order. Also if you have two timestamps, then you can't tell whether there was one in between which you don't have. So I feel timestamps aren't very good for updating a remote context, and it isn't the recommended approach in e.g Vaughn Vernon's Implementing Domain Driven Design. Having said that, it is possible to use a jitter buffer, and run a little bit behind (how much?), which may be the best thing to do if the situation is tolerant of the occasional event missing, the consequent guaranteed latency, and requires more throughput than can be obtained by using integer sequences. The other disappointment with timebucketed logs is that if your timebucket is small, so that you can deal with large spikes of demand, then after a while it will take ages to step through all the buckets, and some may be empty, so it feels inefficient. That issue can be mitigated by having a second timebucketed log with larger sized buckets, and writing into that an event which corresponds to the start of a fine grained time bucket, so that you don't need to read time buckets that contain nothing. Obviously, timebuckets can also be read in parallel...

The trouble with timebucketed logs caused me to investigate using integer sequences, which is the recommended approach in Vaugh Vernon's book. That's why I developed the BigArray class. It constructs a single integer sequence across partitions, is resilient against concurrency, scales bigger than you can imagine, and gives good access times. It can lead to a lot of contention when the last position in the sequence isn't known, so you have to read the last position, and then attempt to write, but if another thread gets in before you, your thread gets a concurrency error and you have to start the command again. But with a separate integer sequence generator, all the contention goes away, and it will have write performance comparable to the timebucketed log. The separate integer sequence generator, however may constitute a single point of failure, although that can also be mitigated with a little bit of effort (it can certainly be made reliable, but perhaps not to have perfect availability). Then, since there is a single sequence of integers, projections and remote contexts can know if they are missing an event and can catch up.

So I'm thinking, if it's possible to construct these application-wide logs whilst the events are being written to their partitions, that will really help to propagate the events with high fidelity. And for an application that doesn't have such a thing, then it would be possible to construct it later, either by firstly generating a time bucketed log and making an application sequence from that, or by using perhaps a priority queue to accomplish the same thing in memory.

But the place to start, I feel is getting all the partition keys, as you have done. Except fixing it to use the token, in case there are too many to get with one query. In other words, something like this:

```

    def all_sequence_id(self):
        query = self.active_record_class.objects.all().limit(1)
        page = list(query)
        while page:
            for record in page:
                yield record.pk
            last = page[-1]
            page = list(query.filter(pk__token__gt=Token(last.pk)))
```

But adjusted so you can pass in a pk, and resume. I'll fix the develop branch to do it like this, ASAP.

PS Sorry for the long reply. This area is kinda the "last problem" I need to solve with this library, and finding a way to do it that will work at "volume" and "velocity" has been bugging me for ages. :-)

**Comment by yarbelkgazia** [comment]
I <3 the long reply.

This domain for me does not need to scale, so I will continue as I had.  I'm glad to see how much though you've put into this.  I know cochroachdb - a cloud-native distributed SQL server - has a solution to the clock skew problem.  I haven't read through the code and only glanced at their writeup: https://www.cockroachlabs.com/blog/living-without-atomic-clocks/ but it discusses the same problems on linearizability and serializeability.

**Comment by johnbywater** [comment]
Interesting link. The idea of having a central timestamp service is similar to having a central integer sequence service. The idea of passing something through the "causal chain" never occurred to me. I guess if an application is event driven, the event will have a timestamp, and downstream could just make sure they never timestamp events with an earlier value. (Could that work?) Centralised or otherwise, timestamps don't allow downstream to know whether a notification is missing. Waiting for things sounds like throughput would drop quite a lot? I don't fully understand the actual design they describe at the end of the article, how they avoid "time of check to time of use" issues when checking for the latest timestamp on nodes they are writing to before writing to the nodes. It's a tricky area eh.

**Comment by yarbelkgazia** [comment]
Yeah,  I thought it was a very interesting solution.  I've been meaning to
find the part of the code where this is done so I can get a better
understanding of the implementation and the actual algorithm.

**Comment by johnbywater** [comment]
Have changed the active record strategy to do this in a better way:
https://github.com/johnbywater/eventsourcing/blob/develop/eventsourcing/infrastructure/cassandra/activerecords.py#L87

https://github.com/johnbywater/eventsourcing/blob/develop/eventsourcing/infrastructure/cassandra/activerecords.py#L100

Seems to be working, so am closing this issue. Please reopen otherwise.
